#define DIA "Ingrese el N° de día"
#define INICIO "Ingrese el primer día del año en N°, dom = 1, lun = 2, ..., sáb = 7"
#define ERROR "ERROR"
#define ERROR_RANGO "Valor fuera del rango posible"
#define ERROR_DEC "Carácter inválido"
