#define CANT "Ingrese la cantidad de viajes realizados"
#define KM "Ingrese los kilómetros recorridos (-1 para terminar)"
#define PRE "Ingrese el precio del combustible por litro"
#define GASTO "Ingrese el monto total utilizado en esta compra"
#define REND "Rendimiento (l/100km) de este tanque:"
#define REND_PROM "Rendimiento promedio (l/100km):"
#define MEJ_REND "Mejor rendimiento (l/100km):"
#define PEOR_REND "Peor rendimiento (l/100km):"
#define DIST "Distancia total recorrida (km):"
#define COMB "Combustible total consumidos (l):"
#define COST_TOT "Costo total de su vehículo ($):"
#define ERROR "ERROR"
#define ERROR_RANGO "Valor fuera del rango posible"
#define ERROR_DEC "Carácter no válido"
